### ISSUE TITLE
Description of run-length encoding in .256 files

### ISSUE THREAD

**Issue by jonathaningram** [madwareru/orom-file-formats#15]
Hi, thanks for sharing these spec files. In the .256 spec you talk about run-length encoding (see https://github.com/madwareru/orom-file-formats/blob/95c84cd521aed2601f4717399cbb01f175004c06/KSY/images/rom_256.ksy#L10), but in `orom-first-encounters` I can't seem to find where you actually do that decoding? Are you able to point me in the right direction for this? E.g. documentation.

Out of interest, have you decoded all of the RoM formats yourself or did you have a reference spec that you used?

**Comment by madwareru** [comment]
Hi Jonathan!

> I can't seem to find where you actually do that decoding? Are you able to point me in the right direction for this?

Decoding of a file is being made directly at a time of rendition. The code you should be interested lies in this function: https://github.com/madwareru/orom-first-encounter/blob/master/src/graphics/Sprite256.cpp#L179

> Out of interest, have you decoded all of the RoM formats yourself or did you have a reference spec that you used?
These formats where inspected in a huge detail long time ago by a russian community of a game.
Most of information about formats I took from repos of this guy https://github.com/jewalky
But he is mainly focused on RoM 2, so I've being forced to inspect formats specific for RoM 1 by myself.

Thanks for the attention for my work by the way, if you will have any other questions, feel free to ask :)

**Comment by madwareru** [comment]
You can be interested in this version of a code, which is much more convenient in a case of decoding into a normal texture: https://github.com/jewalky/UnityAllods/blob/c96d24474b882440d2ec181f6dc6dc85062bc681/Assets/Data/Images.cs#L463

**Comment by jonathaningram** [comment]
@madwareru thank you for getting back to me. And thanks for sharing the exact link in the code. I'll look into it a bit closer and see if I can work out what's happening. It's really great that you've open sourced this work so that people like me can get the benefits of all the hard work you and the original community put into researching the RoM formats. And yes, I may have some more questions along the way :)
